siteTitle="WytheMe"
baseColor = "#3F51B5"
linkPrefix = "/gatsby-starter-documentation"
docPages = [
  "/docs/",
  "/docs/getting-started/",
  "/docs/how-to-run/",
  "/docs/some-react-code/",
  "/docs/the-next-step/",
  "/docs/conclusion/",
  "/docs/react-native-and-strophe/",
]


